### ISSUE TITLE
Использование пользовательских данных

### ISSUE THREAD

**Issue by skittonik** [osov/defold-yandex-sdk-ads#3]
Мне отклонили в Play Market игру по "Безопасности данных", написали что приложение использует "Идентификаторы устройства или другие идентификаторы" / "Version code 1: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address)".

РСЯ на своей странице пишет что по умолчанию все отключено (я отметил так же):
https://ads.yandex.com/helpcenter/ru/dev/android/app-privacy-android

Так вот, экстеншен как-то использует пользовательские данные? И если да, то можете ли подсказать что указать в "Безопасности данных"?

**Comment by osov** [comment]
https://ads.yandex.com/helpcenter/ru/dev/android/app-privacy-android
Тут в самом низу написано "Идентификаторы устройства или другие идентификаторы - ДА", так вот как минимум это и указать нужно.
А вот что именно указать в "Безопасности данных" я не скажу, т.к. сам не занимаюсь размещением.
